#Alacritty:

env:
  TERM: alacritty

window:
  opacity: 1.0
  padding:
    x: 25
    y: 25

    dynamic_padding:  true
    decoration: none

font:
  normal:
    family: Source Code Pro

  bold:
    family: Source Code Pro

  italic:
    family: Source Code Pro

  bold_italic:
    family: Source Code Pro

  size: 9

colors:
  # Default colors
  primary:
    background: '0x181a20'
    foreground: '0xeeffff'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x212121'
    cursor: '0xeeffff'

  # Normal colors
  normal:
    black:   '0x212121'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xeeffff'

  # Bright colors
  bright:
    black:   '0x4a4a4a'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xffffff'

  indexed_colors:
    - { index: 16, color: '0xf78c6c' }
    - { index: 17, color: '0xff5370' }
    - { index: 18, color: '0x303030' }
    - { index: 19, color: '0x353535' }
    - { index: 20, color: '0xb2ccd6' }
    - { index: 21, color: '0xeeffff' }

# cursor:
#   style: Underline

#   unfocused_hollow: false

live_config_reload: true
                 
key_bindings:

  - { key: Key0, mods: Control, action: ResetFontSize }

  - { key: Equals, mods: Control, action: IncreaseFontSize }

  - { key: Minus, mods: Control, action: DecreaseFontSize }
